# Generated by Django 5.2.5 on 2026-09-25 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessmentblueprint'),
        ('careers', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_count', models.PositiveIntegerField(default=3)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('difficulty_distribution', models.JSONField(blank=True, default=dict)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_skills', to='assessments.assessmentblueprint')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprint_skills', to='careers.skill')),
            ],
        ),
    ]
