# Generated by Django 5.2.5 on 2026-09-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_blueprintskill'),
        ('careers', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('OPEN_ENDED', 'Open Ended'), ('CODE', 'Coding')], default='MCQ', max_length=20)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=10)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=1)),
                ('source', models.CharField(choices=[('AI', 'AI Generated'), ('ADMIN', 'Admin Created'), ('IMPORTED', 'Imported')], default='AI', max_length=20)),
                ('ai_generated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessment')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='careers.skill')),
            ],
        ),
    ]
