# Generated by Django 5.2.5 on 2026-09-26 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_aievaluation'),
        ('careers', '0002_alter_category_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('proficiency_level', models.CharField(max_length=50)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_results', to='assessments.assessmentattempt')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='careers.skill')),
            ],
        ),
    ]
